clip_output_dir: "/tmp"
max_clip_radius_sec: 30
max_inmem_data_mbs: 100
max_clip_io_mbs_per_sec: 10

clip_setting:
  bag_topics_mapping:
    sensor:
      - /sensor/camera/rear_camera/encode
      - /sensor/dual_antenna_heading
      - /sensor/dual_antenna_heading/rear_center_ins_bynav
      - /sensor/dual_antenna_heading/rear_center_ins_novatel
      - /sensor/gnss
      - /sensor/gnss/asensing
      - /sensor/gnss/rear_center_ins_bynav
      - /sensor/gnss/rear_center_ins_novatel
      - /sensor/imu
      - /sensor/imu/asensing
      - /sensor/imu/rear_center_ins_bynav
      - /sensor/imu/rear_center_ins_novatel
      - /sensor/ins
      - /sensor/ins/asensing
      - /sensor/ins/rear_center_ins_bynav
      - /sensor/ins/rear_center_ins_novatel
      - /sensor/radar
      - /sensor/radar/front_left_radar
      - /sensor/radar/front_radar
      - /sensor/radar/front_right_radar
      - /sensor/radar/rear_left_radar
      - /sensor/radar/rear_radar
      - /sensor/radar/rear_right_radar
      - /sensor/uss
      - /sensor/camera/center_camera_fov120/encode
      - /sensor/camera/center_camera_fov30/encode
      - /sensor/camera/left_front_camera/encode
      - /sensor/camera/left_rear_camera/encode
      - /sensor/camera/rear_camera/encode
      - /sensor/camera/right_front_camera/encode
      - /sensor/camera/right_rear_camera/encode
      - /sensor/camera/front_camera_fov195/encode
      - /sensor/camera/left_camera_fov195/encode
      - /sensor/camera/rear_camera_fov195/encode
      - /sensor/camera/right_camera_fov195/encode
    sensor_raw:
      - /sensor/uss/raw
      - /sensor/ins/raw
      - /sensor/canbus/raw
      - /sensor/front_radar/raw
      - /sensor/front_left_radar/raw
      - /sensor/rear_left_radar/raw
      - /sensor/rear_radar/raw
      - /sensor/rear_right_radar/raw
      - /sensor/front_right_radar/raw
      - /sensor/top_center_lidar/raw
    other:
      - /perception/center_camera_fov120_gop/object
      - /perception/center_camera_fov120/env_odd
      - /perception/center_camera_fov120/object
      - /perception/center_camera_fov120/road_geometry
      - /perception/center_camera_fov120/road_semantics
      - /perception/center_camera_fov30_gop/object
      - /perception/center_camera_fov30/env_odd
      - /perception/center_camera_fov30/object
      - /perception/center_camera_fov30/road_geometry
      - /perception/center_camera_fov30/road_semantics
      - /perception/front_left_radar/object
      - /perception/front_radar/object
      - /perception/front_radar/radar_road_side
      - /perception/front_right_radar/object
      - /perception/fusion/object
      - /perception/fusion/raw_object
      - /perception/fusionlane
      - /perception/left_front_camera/env_odd
      - /perception/left_front_camera/object
      - /perception/left_front_camera/road_geometry
      - /perception/left_front_camera/road_semantics
      - /perception/left_rear_camera/env_odd
      - /perception/left_rear_camera/object
      - /perception/left_rear_camera/road_geometry
      - /perception/left_rear_camera/road_semantics
      - /perception/nv_cameras_center_camera_fov120/obiect
      - /perception/nv_cameras_left_front_camera/object
      - /perception/nv_cameras_left_rear_camera/object
      - /perception/nv_cameras_rear_camera/obiect
      - /perception/nv_cameras_right_front_camera/object
      - /perception/nv_cameras_right_rear_camera/object
      - /perception/nv_cameras/object
      - /perception/nv_cameras/road_geometry
      - /perception/radar/object
      - /perception/rear_camera/env_odd
      - /perception/rear_camera/object
      - /perception/rear_camera/road_geometry
      - /perception/rear_camera/road_semantics
      - /perception/rear_left_radar/object
      - /perception/rear_radar/object
      - /perception/rear_right_radar/object
      - /perception/right_front_camera/env_odd
      - /perception/right_front_camera/object
      - /perception/right_front_camera/road_geometry
      - /perception/right_front_camera/road_semantics
      - /perception/right_rear_camera/env_odd
      - /perception/right_rear_camera/object
      - /perception/right_rear_camera/road_geometry
      - /perception/right_rear_camera/road_semantics
      - /canbus/vehicle_report
      - /localization/odomstate_info

full_clip_setting:
  delay_start: true
  bag_topics_mapping:
    sensor_bag:
      - /sensor/camera/eval_data
      - /sensor/gnss
      - /sensor/gnss/rear_center_ins_bynav
      - /sensor/imu
      - /sensor/ins
      - /sensor/ins/rear_center_ins_bynav
      - /sensor/dual_antenna_heading
      - /sensor/radar
      - /sensor/uss/bosch_pas
      - /sensor/uss/long_range_uss
    perception:
      - /perception/nv_cameras/object
      - /perception/nv_cameras_center_camera_fov120/obiect
      - /perception/nv_cameras_left_front_camera/object
      - /perception/nv_cameras_left_rear_camera/object
      - /perception/nv_cameras_rear_camera/obiect
      - /perception/nv_cameras_right_front_camera/object
      - /perception/nv_cameras_right_rear_camera/object
      - /perception/center_camera_fov120/env_odd
      - /perception/center_camera_fov120/object
      - /perception/center_camera_fov120/road_geometry
      - /perception/center_camera_fov120/road_semantics
      - /perception/center_camera_fov120/failsafe
      - /perception/center_camera_fov30/env_odd
      - /perception/center_camera_fov30/object
      - /perception/center_camera_fov30/road_geometry
      - /perception/center_camera_fov30/road_semantics
      - /perception/center_camera_fov30/failsafe
      - /perception/center_camera_fov30/gop_object
      - /perception/nv_cameras/road_geometry
      - /perception/nv_cameras/gop_object
      - /perception/nv_cameras/occ_info
      - /perception/nv_cameras/road_topology
      - /perception/center_camera_fov120_gop/object
      - /perception/center_camera_fov30_gop/object
      - /perception/front_left_radar/object
      - /perception/front_radar/object
      - /perception/front_radar/radar_road_side
      - /perception/front_right_radar/object
      - /perception/fusion/object
      - /perception/fusion/raw_object
      - /perception/left_front_camera/env_odd
      - /perception/left_front_camera/object
      - /perception/left_front_camera/road_geometry
      - /perception/left_front_camera/road_semantics
      - /perception/left_front_camera/failsafe
      - /perception/left_rear_camera/env_odd
      - /perception/left_rear_camera/object
      - /perception/left_rear_camera/road_geometry
      - /perception/left_rear_camera/road_semantics
      - /perception/left_rear_camera/failsafe
      - /perception/radar/object
      - /perception/rear_camera/env_odd
      - /perception/rear_camera/object
      - /perception/rear_camera/road_geometry
      - /perception/rear_camera/road_semantics
      - /perception/rear_camera/failsafe
      - /perception/rear_left_radar/object
      - /perception/rear_radar/object
      - /perception/rear_right_radar/object
      - /perception/right_front_camera/env_odd
      - /perception/right_front_camera/object
      - /perception/right_front_camera/road_geometry
      - /perception/right_front_camera/road_semantics
      - /perception/right_front_camera/failsafe
      - /perception/right_rear_camera/env_odd
      - /perception/right_rear_camera/object
      - /perception/right_rear_camera/road_geometry
      - /perception/right_rear_camera/road_semantics
      - /perception/right_rear_camera/failsafe
      - /perception/fusionlane
      - /perception/fusionlane/udp
      - /perception/fusion/object/udp
      - /perception/nv_cameras/object/udp
      - /perception/lidar/object
      - /perception/lidar_gop/object
    others:
      - /canbus/vehicle_report
      - /canbus/vehicle_command
      - /canbus/chassis_acan
      - /canbus/act_acan
      - /control/control_debug
      - /control/dmc_debug
      - /hdmap/road_structure
      - /hdmap/route_info
      - /hdmap/sub_map
      - /localization/odomstate_info
      - /monitor/monitor_report
      - /monitor/laelaps_info
      - /parking/avp_state_machine/state_broadcast
      - /parking/control/control_debug
      - /parking/control/controlstate
      - /parking/decision_planning/parking_slots
      - /parking/decision_planning/reference_line_lane_line
      - /parking/decision_planning/scenario_model_debug
      - /parking/decision_planning/target_slot
      - /parking/decision_planning/trajectory
      - /parking/decision_planning/turn_reminder
      - /parking/hmi/hmi_command
      - /parking/hmi/hmi_single_command
      - /parking/hmi/parking_cmd
      - /parking/localization/navstate_info
      - /parking/perception/camera/fisheye_objects
      - /parking/perception/camera/fisheye_objects_world
      - /parking/perception/camera/fsline_points
      - /parking/perception_camera_ipm_image
      - /parking/perception_camera_freespace_gridmap
      - /parking/perception/fusion_parking_slots
      - /parking/smart_slam/map_info
      - /parking/plan/status_info
      - /prediction/objects
      - /ehr/sdmap
      - /decision_planning/decision_debug
      - /decision_planning/decision_output
      - /decision_planning/decision_target
      - /decision_planning/planning_debug
      - /decision_planning/trajectory
      - /decision_planning/drivercmdinfo
      - /scenario_model/reference_lanes
      - /scenario_model/relative_localization
      - /xpilot/xdebug
      - /holo/road_structure
      - /nop/planning/trajectory
      - /canbus/mrr
      - /decision_planning/planning_state
      - /nop/hmi/panel
      - /tencent_map/nav_route/info
      - /maplesslm/odomstate_info
      - /maplesslm/scene_navi_map
      - /maplesslm/scene_navi_map_online
      - /xpilot/lfp
      - /mcu/nop_status
      - /mcu/state_machine
      - /mcu/vehicle_processing
      - /mcu/low_ctrl
      - /mcu/low_ctrl/udp
      - /mcu/vehicle/udp
      - /mcu/sensor_bus_object/udp
      - /mcu/sensor_5r1v_extra/udp
      - /mcu/control_platform/udp
      - /mcu/referline/udp
      - /mcu/control2hmi/udp
      - /mcu/trajectory/udp
      - /mcu/nop_status/udp
      - /mcu/vehicle_processing/udp
      - /mcu/state_machine/udp
      - /mcu/papstatus_out/udp
      - /scenario_model/reference_lanes/udp
      - /scenario_model/relative_localization/udp
      - /decision_planning/trajectory/udp
      - /decision_planning/planning_state/udp
      - /canbus/vehicle_command/udp
      - /localization/odomstate_info/udp
      - /pap_state_machine/pap_parkingreg/udp
      - /pap_em/em_state/udp
      - /parking/perception/uss/obstacles
      - /hmi/pap_switch_req
      - /hmi/pap_switch_resp
      - /pap_state_machine/pap_parkingreq
      - /mcu/papstatus_out
      - /pap_em/em_state
      - /cid/can_data
      - /parking/slam/status_info
      - /parking/uic_fsm/cmd
      - /parking/control/status_info
      - /parking/plan/status_info
      - /parking/fusion/status_info
      - /parking/hmi/uic/visualizer
