// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: um.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 10002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(bb7b76341b8de1b5);
enum class StateMachine_bb7b76341b8de1b5: uint16_t {
  OTA_I_D_E_L,
  OTA_P_R_E_U_P_D_A_T_E,
  OTA_U_P_D_A_T_I_N_G,
  OTA_U_P_D_A_T_E_D,
  OTA_A_C_T_I_V_I_N_G,
  OTA_A_C_T_I_V_E_D,
};
CAPNP_DECLARE_ENUM(StateMachine, bb7b76341b8de1b5);
CAPNP_DECLARE_SCHEMA(d94509964c45c9e8);

}  // namespace schemas
}  // namespace capnp

namespace senseAD {
namespace msg {
namespace um {

typedef ::capnp::schemas::StateMachine_bb7b76341b8de1b5 StateMachine;

struct OtaMessage {
  OtaMessage() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d94509964c45c9e8, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class OtaMessage::Reader {
public:
  typedef OtaMessage Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::senseAD::msg::um::StateMachine getStateMachine() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class OtaMessage::Builder {
public:
  typedef OtaMessage Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::senseAD::msg::um::StateMachine getStateMachine();
  inline void setStateMachine( ::senseAD::msg::um::StateMachine value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class OtaMessage::Pipeline {
public:
  typedef OtaMessage Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::senseAD::msg::um::StateMachine OtaMessage::Reader::getStateMachine() const {
  return _reader.getDataField< ::senseAD::msg::um::StateMachine>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::senseAD::msg::um::StateMachine OtaMessage::Builder::getStateMachine() {
  return _builder.getDataField< ::senseAD::msg::um::StateMachine>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void OtaMessage::Builder::setStateMachine( ::senseAD::msg::um::StateMachine value) {
  _builder.setDataField< ::senseAD::msg::um::StateMachine>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

}  // namespace
}  // namespace
}  // namespace

CAPNP_END_HEADER

