// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: planning_mode.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 10002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(eebdd3d4cd04ecd7);
CAPNP_DECLARE_SCHEMA(c7eaed121803ea9b);
CAPNP_DECLARE_SCHEMA(b74ff81373b6aa95);
CAPNP_DECLARE_SCHEMA(dc63188a0361bb40);
CAPNP_DECLARE_SCHEMA(d281bcecc8c04c79);
CAPNP_DECLARE_SCHEMA(f0003e13959e4099);
CAPNP_DECLARE_SCHEMA(e2fc6e2973e1dba6);
CAPNP_DECLARE_SCHEMA(966c6f26a8751545);

}  // namespace schemas
}  // namespace capnp

namespace senseAD {
namespace planning {
namespace msg {

struct NoneParam {
  NoneParam() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(eebdd3d4cd04ecd7, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ApaParam {
  ApaParam() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(c7eaed121803ea9b, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct HppParam {
  HppParam() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(b74ff81373b6aa95, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct HpmParam {
  HpmParam() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(dc63188a0361bb40, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct StandbyParam {
  StandbyParam() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d281bcecc8c04c79, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ChangeModeRequest {
  ChangeModeRequest() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  struct Param;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(f0003e13959e4099, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ChangeModeRequest::Param {
  Param() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    APA_PARAM,
    HPP_PARAM,
    HPM_PARAM,
    STANDBY_PARAM,
    NONE_PARAM,
  };

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(e2fc6e2973e1dba6, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

struct ChangeModeResponse {
  ChangeModeResponse() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(966c6f26a8751545, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class NoneParam::Reader {
public:
  typedef NoneParam Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class NoneParam::Builder {
public:
  typedef NoneParam Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class NoneParam::Pipeline {
public:
  typedef NoneParam Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ApaParam::Reader {
public:
  typedef ApaParam Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getSlotId() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ApaParam::Builder {
public:
  typedef ApaParam Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::uint64_t getSlotId();
  inline void setSlotId( ::uint64_t value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ApaParam::Pipeline {
public:
  typedef ApaParam Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class HppParam::Reader {
public:
  typedef HppParam Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class HppParam::Builder {
public:
  typedef HppParam Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class HppParam::Pipeline {
public:
  typedef HppParam Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class HpmParam::Reader {
public:
  typedef HpmParam Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class HpmParam::Builder {
public:
  typedef HpmParam Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class HpmParam::Pipeline {
public:
  typedef HpmParam Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class StandbyParam::Reader {
public:
  typedef StandbyParam Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class StandbyParam::Builder {
public:
  typedef StandbyParam Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class StandbyParam::Pipeline {
public:
  typedef StandbyParam Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ChangeModeRequest::Reader {
public:
  typedef ChangeModeRequest Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline typename Param::Reader getParam() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ChangeModeRequest::Builder {
public:
  typedef ChangeModeRequest Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline typename Param::Builder getParam();
  inline typename Param::Builder initParam();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ChangeModeRequest::Pipeline {
public:
  typedef ChangeModeRequest Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

  inline typename Param::Pipeline getParam();
private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ChangeModeRequest::Param::Reader {
public:
  typedef Param Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline bool isApaParam() const;
  inline bool hasApaParam() const;
  inline  ::senseAD::planning::msg::ApaParam::Reader getApaParam() const;

  inline bool isHppParam() const;
  inline bool hasHppParam() const;
  inline  ::senseAD::planning::msg::HppParam::Reader getHppParam() const;

  inline bool isHpmParam() const;
  inline bool hasHpmParam() const;
  inline  ::senseAD::planning::msg::HppParam::Reader getHpmParam() const;

  inline bool isStandbyParam() const;
  inline bool hasStandbyParam() const;
  inline  ::senseAD::planning::msg::StandbyParam::Reader getStandbyParam() const;

  inline bool isNoneParam() const;
  inline bool hasNoneParam() const;
  inline  ::senseAD::planning::msg::NoneParam::Reader getNoneParam() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ChangeModeRequest::Param::Builder {
public:
  typedef Param Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline bool isApaParam();
  inline bool hasApaParam();
  inline  ::senseAD::planning::msg::ApaParam::Builder getApaParam();
  inline void setApaParam( ::senseAD::planning::msg::ApaParam::Reader value);
  inline  ::senseAD::planning::msg::ApaParam::Builder initApaParam();
  inline void adoptApaParam(::capnp::Orphan< ::senseAD::planning::msg::ApaParam>&& value);
  inline ::capnp::Orphan< ::senseAD::planning::msg::ApaParam> disownApaParam();

  inline bool isHppParam();
  inline bool hasHppParam();
  inline  ::senseAD::planning::msg::HppParam::Builder getHppParam();
  inline void setHppParam( ::senseAD::planning::msg::HppParam::Reader value);
  inline  ::senseAD::planning::msg::HppParam::Builder initHppParam();
  inline void adoptHppParam(::capnp::Orphan< ::senseAD::planning::msg::HppParam>&& value);
  inline ::capnp::Orphan< ::senseAD::planning::msg::HppParam> disownHppParam();

  inline bool isHpmParam();
  inline bool hasHpmParam();
  inline  ::senseAD::planning::msg::HppParam::Builder getHpmParam();
  inline void setHpmParam( ::senseAD::planning::msg::HppParam::Reader value);
  inline  ::senseAD::planning::msg::HppParam::Builder initHpmParam();
  inline void adoptHpmParam(::capnp::Orphan< ::senseAD::planning::msg::HppParam>&& value);
  inline ::capnp::Orphan< ::senseAD::planning::msg::HppParam> disownHpmParam();

  inline bool isStandbyParam();
  inline bool hasStandbyParam();
  inline  ::senseAD::planning::msg::StandbyParam::Builder getStandbyParam();
  inline void setStandbyParam( ::senseAD::planning::msg::StandbyParam::Reader value);
  inline  ::senseAD::planning::msg::StandbyParam::Builder initStandbyParam();
  inline void adoptStandbyParam(::capnp::Orphan< ::senseAD::planning::msg::StandbyParam>&& value);
  inline ::capnp::Orphan< ::senseAD::planning::msg::StandbyParam> disownStandbyParam();

  inline bool isNoneParam();
  inline bool hasNoneParam();
  inline  ::senseAD::planning::msg::NoneParam::Builder getNoneParam();
  inline void setNoneParam( ::senseAD::planning::msg::NoneParam::Reader value);
  inline  ::senseAD::planning::msg::NoneParam::Builder initNoneParam();
  inline void adoptNoneParam(::capnp::Orphan< ::senseAD::planning::msg::NoneParam>&& value);
  inline ::capnp::Orphan< ::senseAD::planning::msg::NoneParam> disownNoneParam();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ChangeModeRequest::Param::Pipeline {
public:
  typedef Param Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

class ChangeModeResponse::Reader {
public:
  typedef ChangeModeResponse Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline bool getOk() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ChangeModeResponse::Builder {
public:
  typedef ChangeModeResponse Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline bool getOk();
  inline void setOk(bool value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ChangeModeResponse::Pipeline {
public:
  typedef ChangeModeResponse Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::uint64_t ApaParam::Reader::getSlotId() const {
  return _reader.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint64_t ApaParam::Builder::getSlotId() {
  return _builder.getDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ApaParam::Builder::setSlotId( ::uint64_t value) {
  _builder.setDataField< ::uint64_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline typename ChangeModeRequest::Param::Reader ChangeModeRequest::Reader::getParam() const {
  return typename ChangeModeRequest::Param::Reader(_reader);
}
inline typename ChangeModeRequest::Param::Builder ChangeModeRequest::Builder::getParam() {
  return typename ChangeModeRequest::Param::Builder(_builder);
}
#if !CAPNP_LITE
inline typename ChangeModeRequest::Param::Pipeline ChangeModeRequest::Pipeline::getParam() {
  return typename ChangeModeRequest::Param::Pipeline(_typeless.noop());
}
#endif  // !CAPNP_LITE
inline typename ChangeModeRequest::Param::Builder ChangeModeRequest::Builder::initParam() {
  _builder.setDataField< ::uint16_t>(::capnp::bounded<0>() * ::capnp::ELEMENTS, 0);
  _builder.getPointerField(::capnp::bounded<0>() * ::capnp::POINTERS).clear();
  return typename ChangeModeRequest::Param::Builder(_builder);
}
inline  ::senseAD::planning::msg::ChangeModeRequest::Param::Which ChangeModeRequest::Param::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline  ::senseAD::planning::msg::ChangeModeRequest::Param::Which ChangeModeRequest::Param::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool ChangeModeRequest::Param::Reader::isApaParam() const {
  return which() == ChangeModeRequest::Param::APA_PARAM;
}
inline bool ChangeModeRequest::Param::Builder::isApaParam() {
  return which() == ChangeModeRequest::Param::APA_PARAM;
}
inline bool ChangeModeRequest::Param::Reader::hasApaParam() const {
  if (which() != ChangeModeRequest::Param::APA_PARAM) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ChangeModeRequest::Param::Builder::hasApaParam() {
  if (which() != ChangeModeRequest::Param::APA_PARAM) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::senseAD::planning::msg::ApaParam::Reader ChangeModeRequest::Param::Reader::getApaParam() const {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::APA_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::ApaParam>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::senseAD::planning::msg::ApaParam::Builder ChangeModeRequest::Param::Builder::getApaParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::APA_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::ApaParam>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::setApaParam( ::senseAD::planning::msg::ApaParam::Reader value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::APA_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::ApaParam>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::senseAD::planning::msg::ApaParam::Builder ChangeModeRequest::Param::Builder::initApaParam() {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::APA_PARAM);
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::ApaParam>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::adoptApaParam(
    ::capnp::Orphan< ::senseAD::planning::msg::ApaParam>&& value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::APA_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::ApaParam>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::senseAD::planning::msg::ApaParam> ChangeModeRequest::Param::Builder::disownApaParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::APA_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::ApaParam>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ChangeModeRequest::Param::Reader::isHppParam() const {
  return which() == ChangeModeRequest::Param::HPP_PARAM;
}
inline bool ChangeModeRequest::Param::Builder::isHppParam() {
  return which() == ChangeModeRequest::Param::HPP_PARAM;
}
inline bool ChangeModeRequest::Param::Reader::hasHppParam() const {
  if (which() != ChangeModeRequest::Param::HPP_PARAM) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ChangeModeRequest::Param::Builder::hasHppParam() {
  if (which() != ChangeModeRequest::Param::HPP_PARAM) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::senseAD::planning::msg::HppParam::Reader ChangeModeRequest::Param::Reader::getHppParam() const {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::HPP_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::senseAD::planning::msg::HppParam::Builder ChangeModeRequest::Param::Builder::getHppParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::HPP_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::setHppParam( ::senseAD::planning::msg::HppParam::Reader value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::HPP_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::senseAD::planning::msg::HppParam::Builder ChangeModeRequest::Param::Builder::initHppParam() {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::HPP_PARAM);
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::adoptHppParam(
    ::capnp::Orphan< ::senseAD::planning::msg::HppParam>&& value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::HPP_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::senseAD::planning::msg::HppParam> ChangeModeRequest::Param::Builder::disownHppParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::HPP_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ChangeModeRequest::Param::Reader::isHpmParam() const {
  return which() == ChangeModeRequest::Param::HPM_PARAM;
}
inline bool ChangeModeRequest::Param::Builder::isHpmParam() {
  return which() == ChangeModeRequest::Param::HPM_PARAM;
}
inline bool ChangeModeRequest::Param::Reader::hasHpmParam() const {
  if (which() != ChangeModeRequest::Param::HPM_PARAM) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ChangeModeRequest::Param::Builder::hasHpmParam() {
  if (which() != ChangeModeRequest::Param::HPM_PARAM) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::senseAD::planning::msg::HppParam::Reader ChangeModeRequest::Param::Reader::getHpmParam() const {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::HPM_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::senseAD::planning::msg::HppParam::Builder ChangeModeRequest::Param::Builder::getHpmParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::HPM_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::setHpmParam( ::senseAD::planning::msg::HppParam::Reader value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::HPM_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::senseAD::planning::msg::HppParam::Builder ChangeModeRequest::Param::Builder::initHpmParam() {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::HPM_PARAM);
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::adoptHpmParam(
    ::capnp::Orphan< ::senseAD::planning::msg::HppParam>&& value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::HPM_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::senseAD::planning::msg::HppParam> ChangeModeRequest::Param::Builder::disownHpmParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::HPM_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::HppParam>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ChangeModeRequest::Param::Reader::isStandbyParam() const {
  return which() == ChangeModeRequest::Param::STANDBY_PARAM;
}
inline bool ChangeModeRequest::Param::Builder::isStandbyParam() {
  return which() == ChangeModeRequest::Param::STANDBY_PARAM;
}
inline bool ChangeModeRequest::Param::Reader::hasStandbyParam() const {
  if (which() != ChangeModeRequest::Param::STANDBY_PARAM) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ChangeModeRequest::Param::Builder::hasStandbyParam() {
  if (which() != ChangeModeRequest::Param::STANDBY_PARAM) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::senseAD::planning::msg::StandbyParam::Reader ChangeModeRequest::Param::Reader::getStandbyParam() const {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::STANDBY_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::StandbyParam>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::senseAD::planning::msg::StandbyParam::Builder ChangeModeRequest::Param::Builder::getStandbyParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::STANDBY_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::StandbyParam>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::setStandbyParam( ::senseAD::planning::msg::StandbyParam::Reader value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::STANDBY_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::StandbyParam>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::senseAD::planning::msg::StandbyParam::Builder ChangeModeRequest::Param::Builder::initStandbyParam() {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::STANDBY_PARAM);
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::StandbyParam>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::adoptStandbyParam(
    ::capnp::Orphan< ::senseAD::planning::msg::StandbyParam>&& value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::STANDBY_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::StandbyParam>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::senseAD::planning::msg::StandbyParam> ChangeModeRequest::Param::Builder::disownStandbyParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::STANDBY_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::StandbyParam>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ChangeModeRequest::Param::Reader::isNoneParam() const {
  return which() == ChangeModeRequest::Param::NONE_PARAM;
}
inline bool ChangeModeRequest::Param::Builder::isNoneParam() {
  return which() == ChangeModeRequest::Param::NONE_PARAM;
}
inline bool ChangeModeRequest::Param::Reader::hasNoneParam() const {
  if (which() != ChangeModeRequest::Param::NONE_PARAM) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool ChangeModeRequest::Param::Builder::hasNoneParam() {
  if (which() != ChangeModeRequest::Param::NONE_PARAM) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::senseAD::planning::msg::NoneParam::Reader ChangeModeRequest::Param::Reader::getNoneParam() const {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::NONE_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::NoneParam>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::senseAD::planning::msg::NoneParam::Builder ChangeModeRequest::Param::Builder::getNoneParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::NONE_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::NoneParam>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::setNoneParam( ::senseAD::planning::msg::NoneParam::Reader value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::NONE_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::NoneParam>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::senseAD::planning::msg::NoneParam::Builder ChangeModeRequest::Param::Builder::initNoneParam() {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::NONE_PARAM);
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::NoneParam>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void ChangeModeRequest::Param::Builder::adoptNoneParam(
    ::capnp::Orphan< ::senseAD::planning::msg::NoneParam>&& value) {
  _builder.setDataField<ChangeModeRequest::Param::Which>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, ChangeModeRequest::Param::NONE_PARAM);
  ::capnp::_::PointerHelpers< ::senseAD::planning::msg::NoneParam>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::senseAD::planning::msg::NoneParam> ChangeModeRequest::Param::Builder::disownNoneParam() {
  KJ_IREQUIRE((which() == ChangeModeRequest::Param::NONE_PARAM),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::senseAD::planning::msg::NoneParam>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}

inline bool ChangeModeResponse::Reader::getOk() const {
  return _reader.getDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline bool ChangeModeResponse::Builder::getOk() {
  return _builder.getDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ChangeModeResponse::Builder::setOk(bool value) {
  _builder.setDataField<bool>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

}  // namespace
}  // namespace
}  // namespace

CAPNP_END_HEADER

