// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_rscl/idl/component_conf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
#include "ad_rscl/idl/rscl_qos_profile.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto;
namespace senseAD {
namespace rscl {
namespace idl {
class ReaderOption;
class ReaderOptionDefaultTypeInternal;
extern ReaderOptionDefaultTypeInternal _ReaderOption_default_instance_;
class SyncedComponentConfig;
class SyncedComponentConfigDefaultTypeInternal;
extern SyncedComponentConfigDefaultTypeInternal _SyncedComponentConfig_default_instance_;
class SyncedComponentConfig_CustomParamEntry_DoNotUse;
class SyncedComponentConfig_CustomParamEntry_DoNotUseDefaultTypeInternal;
extern SyncedComponentConfig_CustomParamEntry_DoNotUseDefaultTypeInternal _SyncedComponentConfig_CustomParamEntry_DoNotUse_default_instance_;
class TimerComponentConfig;
class TimerComponentConfigDefaultTypeInternal;
extern TimerComponentConfigDefaultTypeInternal _TimerComponentConfig_default_instance_;
class TimerComponentConfig_CustomParamEntry_DoNotUse;
class TimerComponentConfig_CustomParamEntry_DoNotUseDefaultTypeInternal;
extern TimerComponentConfig_CustomParamEntry_DoNotUseDefaultTypeInternal _TimerComponentConfig_CustomParamEntry_DoNotUse_default_instance_;
}  // namespace idl
}  // namespace rscl
}  // namespace senseAD
PROTOBUF_NAMESPACE_OPEN
template<> ::senseAD::rscl::idl::ReaderOption* Arena::CreateMaybeMessage<::senseAD::rscl::idl::ReaderOption>(Arena*);
template<> ::senseAD::rscl::idl::SyncedComponentConfig* Arena::CreateMaybeMessage<::senseAD::rscl::idl::SyncedComponentConfig>(Arena*);
template<> ::senseAD::rscl::idl::SyncedComponentConfig_CustomParamEntry_DoNotUse* Arena::CreateMaybeMessage<::senseAD::rscl::idl::SyncedComponentConfig_CustomParamEntry_DoNotUse>(Arena*);
template<> ::senseAD::rscl::idl::TimerComponentConfig* Arena::CreateMaybeMessage<::senseAD::rscl::idl::TimerComponentConfig>(Arena*);
template<> ::senseAD::rscl::idl::TimerComponentConfig_CustomParamEntry_DoNotUse* Arena::CreateMaybeMessage<::senseAD::rscl::idl::TimerComponentConfig_CustomParamEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace senseAD {
namespace rscl {
namespace idl {

// ===================================================================

class ReaderOption PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:senseAD.rscl.idl.ReaderOption) */ {
 public:
  inline ReaderOption() : ReaderOption(nullptr) {}
  virtual ~ReaderOption();

  ReaderOption(const ReaderOption& from);
  ReaderOption(ReaderOption&& from) noexcept
    : ReaderOption() {
    *this = ::std::move(from);
  }

  inline ReaderOption& operator=(const ReaderOption& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReaderOption& operator=(ReaderOption&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReaderOption& default_instance();

  static inline const ReaderOption* internal_default_instance() {
    return reinterpret_cast<const ReaderOption*>(
               &_ReaderOption_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ReaderOption& a, ReaderOption& b) {
    a.Swap(&b);
  }
  inline void Swap(ReaderOption* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReaderOption* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReaderOption* New() const final {
    return CreateMaybeMessage<ReaderOption>(nullptr);
  }

  ReaderOption* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReaderOption>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReaderOption& from);
  void MergeFrom(const ReaderOption& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReaderOption* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "senseAD.rscl.idl.ReaderOption";
  }
  protected:
  explicit ReaderOption(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto);
    return ::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kChannelFieldNumber = 1,
    kQosProfileFieldNumber = 2,
    kPendingQueueSizeFieldNumber = 3,
  };
  // optional string channel = 1;
  bool has_channel() const;
  private:
  bool _internal_has_channel() const;
  public:
  void clear_channel();
  const std::string& channel() const;
  void set_channel(const std::string& value);
  void set_channel(std::string&& value);
  void set_channel(const char* value);
  void set_channel(const char* value, size_t size);
  std::string* mutable_channel();
  std::string* release_channel();
  void set_allocated_channel(std::string* channel);
  private:
  const std::string& _internal_channel() const;
  void _internal_set_channel(const std::string& value);
  std::string* _internal_mutable_channel();
  public:

  // optional .senseAD.rscl.idl.QosProfile qos_profile = 2;
  bool has_qos_profile() const;
  private:
  bool _internal_has_qos_profile() const;
  public:
  void clear_qos_profile();
  const ::senseAD::rscl::idl::QosProfile& qos_profile() const;
  ::senseAD::rscl::idl::QosProfile* release_qos_profile();
  ::senseAD::rscl::idl::QosProfile* mutable_qos_profile();
  void set_allocated_qos_profile(::senseAD::rscl::idl::QosProfile* qos_profile);
  private:
  const ::senseAD::rscl::idl::QosProfile& _internal_qos_profile() const;
  ::senseAD::rscl::idl::QosProfile* _internal_mutable_qos_profile();
  public:
  void unsafe_arena_set_allocated_qos_profile(
      ::senseAD::rscl::idl::QosProfile* qos_profile);
  ::senseAD::rscl::idl::QosProfile* unsafe_arena_release_qos_profile();

  // optional uint32 pending_queue_size = 3 [default = 1];
  bool has_pending_queue_size() const;
  private:
  bool _internal_has_pending_queue_size() const;
  public:
  void clear_pending_queue_size();
  ::PROTOBUF_NAMESPACE_ID::uint32 pending_queue_size() const;
  void set_pending_queue_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_pending_queue_size() const;
  void _internal_set_pending_queue_size(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:senseAD.rscl.idl.ReaderOption)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr channel_;
  ::senseAD::rscl::idl::QosProfile* qos_profile_;
  ::PROTOBUF_NAMESPACE_ID::uint32 pending_queue_size_;
  friend struct ::TableStruct_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto;
};
// -------------------------------------------------------------------

class SyncedComponentConfig_CustomParamEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SyncedComponentConfig_CustomParamEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<SyncedComponentConfig_CustomParamEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  SyncedComponentConfig_CustomParamEntry_DoNotUse();
  explicit SyncedComponentConfig_CustomParamEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const SyncedComponentConfig_CustomParamEntry_DoNotUse& other);
  static const SyncedComponentConfig_CustomParamEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SyncedComponentConfig_CustomParamEntry_DoNotUse*>(&_SyncedComponentConfig_CustomParamEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "senseAD.rscl.idl.SyncedComponentConfig.CustomParamEntry.key");
#else
    (void) s;
#endif
    return true;
 }
  static bool ValidateValue(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "senseAD.rscl.idl.SyncedComponentConfig.CustomParamEntry.value");
#else
    (void) s;
#endif
    return true;
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto);
    return ::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto.file_level_metadata[1];
  }

  public:
};

// -------------------------------------------------------------------

class SyncedComponentConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:senseAD.rscl.idl.SyncedComponentConfig) */ {
 public:
  inline SyncedComponentConfig() : SyncedComponentConfig(nullptr) {}
  virtual ~SyncedComponentConfig();

  SyncedComponentConfig(const SyncedComponentConfig& from);
  SyncedComponentConfig(SyncedComponentConfig&& from) noexcept
    : SyncedComponentConfig() {
    *this = ::std::move(from);
  }

  inline SyncedComponentConfig& operator=(const SyncedComponentConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline SyncedComponentConfig& operator=(SyncedComponentConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SyncedComponentConfig& default_instance();

  static inline const SyncedComponentConfig* internal_default_instance() {
    return reinterpret_cast<const SyncedComponentConfig*>(
               &_SyncedComponentConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SyncedComponentConfig& a, SyncedComponentConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(SyncedComponentConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SyncedComponentConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SyncedComponentConfig* New() const final {
    return CreateMaybeMessage<SyncedComponentConfig>(nullptr);
  }

  SyncedComponentConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SyncedComponentConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SyncedComponentConfig& from);
  void MergeFrom(const SyncedComponentConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SyncedComponentConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "senseAD.rscl.idl.SyncedComponentConfig";
  }
  protected:
  explicit SyncedComponentConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto);
    return ::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kCustomParamFieldNumber = 2,
    kReadersFieldNumber = 3,
    kNameFieldNumber = 1,
  };
  // map<string, string> custom_param = 2;
  int custom_param_size() const;
  private:
  int _internal_custom_param_size() const;
  public:
  void clear_custom_param();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_custom_param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_custom_param();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      custom_param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_custom_param();

  // repeated .senseAD.rscl.idl.ReaderOption readers = 3;
  int readers_size() const;
  private:
  int _internal_readers_size() const;
  public:
  void clear_readers();
  ::senseAD::rscl::idl::ReaderOption* mutable_readers(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::senseAD::rscl::idl::ReaderOption >*
      mutable_readers();
  private:
  const ::senseAD::rscl::idl::ReaderOption& _internal_readers(int index) const;
  ::senseAD::rscl::idl::ReaderOption* _internal_add_readers();
  public:
  const ::senseAD::rscl::idl::ReaderOption& readers(int index) const;
  ::senseAD::rscl::idl::ReaderOption* add_readers();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::senseAD::rscl::idl::ReaderOption >&
      readers() const;

  // optional string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // @@protoc_insertion_point(class_scope:senseAD.rscl.idl.SyncedComponentConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      SyncedComponentConfig_CustomParamEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> custom_param_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::senseAD::rscl::idl::ReaderOption > readers_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  friend struct ::TableStruct_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto;
};
// -------------------------------------------------------------------

class TimerComponentConfig_CustomParamEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TimerComponentConfig_CustomParamEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<TimerComponentConfig_CustomParamEntry_DoNotUse, 
    std::string, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> SuperType;
  TimerComponentConfig_CustomParamEntry_DoNotUse();
  explicit TimerComponentConfig_CustomParamEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const TimerComponentConfig_CustomParamEntry_DoNotUse& other);
  static const TimerComponentConfig_CustomParamEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const TimerComponentConfig_CustomParamEntry_DoNotUse*>(&_TimerComponentConfig_CustomParamEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "senseAD.rscl.idl.TimerComponentConfig.CustomParamEntry.key");
#else
    (void) s;
#endif
    return true;
 }
  static bool ValidateValue(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "senseAD.rscl.idl.TimerComponentConfig.CustomParamEntry.value");
#else
    (void) s;
#endif
    return true;
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto);
    return ::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto.file_level_metadata[3];
  }

  public:
};

// -------------------------------------------------------------------

class TimerComponentConfig PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:senseAD.rscl.idl.TimerComponentConfig) */ {
 public:
  inline TimerComponentConfig() : TimerComponentConfig(nullptr) {}
  virtual ~TimerComponentConfig();

  TimerComponentConfig(const TimerComponentConfig& from);
  TimerComponentConfig(TimerComponentConfig&& from) noexcept
    : TimerComponentConfig() {
    *this = ::std::move(from);
  }

  inline TimerComponentConfig& operator=(const TimerComponentConfig& from) {
    CopyFrom(from);
    return *this;
  }
  inline TimerComponentConfig& operator=(TimerComponentConfig&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TimerComponentConfig& default_instance();

  static inline const TimerComponentConfig* internal_default_instance() {
    return reinterpret_cast<const TimerComponentConfig*>(
               &_TimerComponentConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(TimerComponentConfig& a, TimerComponentConfig& b) {
    a.Swap(&b);
  }
  inline void Swap(TimerComponentConfig* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TimerComponentConfig* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TimerComponentConfig* New() const final {
    return CreateMaybeMessage<TimerComponentConfig>(nullptr);
  }

  TimerComponentConfig* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TimerComponentConfig>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TimerComponentConfig& from);
  void MergeFrom(const TimerComponentConfig& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TimerComponentConfig* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "senseAD.rscl.idl.TimerComponentConfig";
  }
  protected:
  explicit TimerComponentConfig(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto);
    return ::descriptor_table_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kCustomParamFieldNumber = 2,
    kNameFieldNumber = 1,
    kIntervalMsFieldNumber = 3,
    kSimTimeIntervalFieldNumber = 4,
  };
  // map<string, string> custom_param = 2;
  int custom_param_size() const;
  private:
  int _internal_custom_param_size() const;
  public:
  void clear_custom_param();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      _internal_custom_param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      _internal_mutable_custom_param();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
      custom_param() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
      mutable_custom_param();

  // optional string name = 1;
  bool has_name() const;
  private:
  bool _internal_has_name() const;
  public:
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // optional uint32 interval_ms = 3;
  bool has_interval_ms() const;
  private:
  bool _internal_has_interval_ms() const;
  public:
  void clear_interval_ms();
  ::PROTOBUF_NAMESPACE_ID::uint32 interval_ms() const;
  void set_interval_ms(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_interval_ms() const;
  void _internal_set_interval_ms(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional bool sim_time_interval = 4 [default = true];
  bool has_sim_time_interval() const;
  private:
  bool _internal_has_sim_time_interval() const;
  public:
  void clear_sim_time_interval();
  bool sim_time_interval() const;
  void set_sim_time_interval(bool value);
  private:
  bool _internal_sim_time_interval() const;
  void _internal_set_sim_time_interval(bool value);
  public:

  // @@protoc_insertion_point(class_scope:senseAD.rscl.idl.TimerComponentConfig)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      TimerComponentConfig_CustomParamEntry_DoNotUse,
      std::string, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING> custom_param_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::uint32 interval_ms_;
  bool sim_time_interval_;
  friend struct ::TableStruct_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ReaderOption

// optional string channel = 1;
inline bool ReaderOption::_internal_has_channel() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ReaderOption::has_channel() const {
  return _internal_has_channel();
}
inline void ReaderOption::clear_channel() {
  channel_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& ReaderOption::channel() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.ReaderOption.channel)
  return _internal_channel();
}
inline void ReaderOption::set_channel(const std::string& value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:senseAD.rscl.idl.ReaderOption.channel)
}
inline std::string* ReaderOption::mutable_channel() {
  // @@protoc_insertion_point(field_mutable:senseAD.rscl.idl.ReaderOption.channel)
  return _internal_mutable_channel();
}
inline const std::string& ReaderOption::_internal_channel() const {
  return channel_.Get();
}
inline void ReaderOption::_internal_set_channel(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  channel_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ReaderOption::set_channel(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  channel_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:senseAD.rscl.idl.ReaderOption.channel)
}
inline void ReaderOption::set_channel(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  channel_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:senseAD.rscl.idl.ReaderOption.channel)
}
inline void ReaderOption::set_channel(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  channel_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:senseAD.rscl.idl.ReaderOption.channel)
}
inline std::string* ReaderOption::_internal_mutable_channel() {
  _has_bits_[0] |= 0x00000001u;
  return channel_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ReaderOption::release_channel() {
  // @@protoc_insertion_point(field_release:senseAD.rscl.idl.ReaderOption.channel)
  if (!_internal_has_channel()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return channel_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReaderOption::set_allocated_channel(std::string* channel) {
  if (channel != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  channel_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), channel,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:senseAD.rscl.idl.ReaderOption.channel)
}

// optional .senseAD.rscl.idl.QosProfile qos_profile = 2;
inline bool ReaderOption::_internal_has_qos_profile() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || qos_profile_ != nullptr);
  return value;
}
inline bool ReaderOption::has_qos_profile() const {
  return _internal_has_qos_profile();
}
inline const ::senseAD::rscl::idl::QosProfile& ReaderOption::_internal_qos_profile() const {
  const ::senseAD::rscl::idl::QosProfile* p = qos_profile_;
  return p != nullptr ? *p : reinterpret_cast<const ::senseAD::rscl::idl::QosProfile&>(
      ::senseAD::rscl::idl::_QosProfile_default_instance_);
}
inline const ::senseAD::rscl::idl::QosProfile& ReaderOption::qos_profile() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.ReaderOption.qos_profile)
  return _internal_qos_profile();
}
inline void ReaderOption::unsafe_arena_set_allocated_qos_profile(
    ::senseAD::rscl::idl::QosProfile* qos_profile) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(qos_profile_);
  }
  qos_profile_ = qos_profile;
  if (qos_profile) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:senseAD.rscl.idl.ReaderOption.qos_profile)
}
inline ::senseAD::rscl::idl::QosProfile* ReaderOption::release_qos_profile() {
  _has_bits_[0] &= ~0x00000002u;
  ::senseAD::rscl::idl::QosProfile* temp = qos_profile_;
  qos_profile_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::senseAD::rscl::idl::QosProfile* ReaderOption::unsafe_arena_release_qos_profile() {
  // @@protoc_insertion_point(field_release:senseAD.rscl.idl.ReaderOption.qos_profile)
  _has_bits_[0] &= ~0x00000002u;
  ::senseAD::rscl::idl::QosProfile* temp = qos_profile_;
  qos_profile_ = nullptr;
  return temp;
}
inline ::senseAD::rscl::idl::QosProfile* ReaderOption::_internal_mutable_qos_profile() {
  _has_bits_[0] |= 0x00000002u;
  if (qos_profile_ == nullptr) {
    auto* p = CreateMaybeMessage<::senseAD::rscl::idl::QosProfile>(GetArena());
    qos_profile_ = p;
  }
  return qos_profile_;
}
inline ::senseAD::rscl::idl::QosProfile* ReaderOption::mutable_qos_profile() {
  // @@protoc_insertion_point(field_mutable:senseAD.rscl.idl.ReaderOption.qos_profile)
  return _internal_mutable_qos_profile();
}
inline void ReaderOption::set_allocated_qos_profile(::senseAD::rscl::idl::QosProfile* qos_profile) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(qos_profile_);
  }
  if (qos_profile) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(qos_profile)->GetArena();
    if (message_arena != submessage_arena) {
      qos_profile = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, qos_profile, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  qos_profile_ = qos_profile;
  // @@protoc_insertion_point(field_set_allocated:senseAD.rscl.idl.ReaderOption.qos_profile)
}

// optional uint32 pending_queue_size = 3 [default = 1];
inline bool ReaderOption::_internal_has_pending_queue_size() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ReaderOption::has_pending_queue_size() const {
  return _internal_has_pending_queue_size();
}
inline void ReaderOption::clear_pending_queue_size() {
  pending_queue_size_ = 1u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReaderOption::_internal_pending_queue_size() const {
  return pending_queue_size_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReaderOption::pending_queue_size() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.ReaderOption.pending_queue_size)
  return _internal_pending_queue_size();
}
inline void ReaderOption::_internal_set_pending_queue_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  pending_queue_size_ = value;
}
inline void ReaderOption::set_pending_queue_size(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_pending_queue_size(value);
  // @@protoc_insertion_point(field_set:senseAD.rscl.idl.ReaderOption.pending_queue_size)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// SyncedComponentConfig

// optional string name = 1;
inline bool SyncedComponentConfig::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SyncedComponentConfig::has_name() const {
  return _internal_has_name();
}
inline void SyncedComponentConfig::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SyncedComponentConfig::name() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.SyncedComponentConfig.name)
  return _internal_name();
}
inline void SyncedComponentConfig::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:senseAD.rscl.idl.SyncedComponentConfig.name)
}
inline std::string* SyncedComponentConfig::mutable_name() {
  // @@protoc_insertion_point(field_mutable:senseAD.rscl.idl.SyncedComponentConfig.name)
  return _internal_mutable_name();
}
inline const std::string& SyncedComponentConfig::_internal_name() const {
  return name_.Get();
}
inline void SyncedComponentConfig::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void SyncedComponentConfig::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:senseAD.rscl.idl.SyncedComponentConfig.name)
}
inline void SyncedComponentConfig::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:senseAD.rscl.idl.SyncedComponentConfig.name)
}
inline void SyncedComponentConfig::set_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:senseAD.rscl.idl.SyncedComponentConfig.name)
}
inline std::string* SyncedComponentConfig::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* SyncedComponentConfig::release_name() {
  // @@protoc_insertion_point(field_release:senseAD.rscl.idl.SyncedComponentConfig.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void SyncedComponentConfig::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:senseAD.rscl.idl.SyncedComponentConfig.name)
}

// map<string, string> custom_param = 2;
inline int SyncedComponentConfig::_internal_custom_param_size() const {
  return custom_param_.size();
}
inline int SyncedComponentConfig::custom_param_size() const {
  return _internal_custom_param_size();
}
inline void SyncedComponentConfig::clear_custom_param() {
  custom_param_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
SyncedComponentConfig::_internal_custom_param() const {
  return custom_param_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
SyncedComponentConfig::custom_param() const {
  // @@protoc_insertion_point(field_map:senseAD.rscl.idl.SyncedComponentConfig.custom_param)
  return _internal_custom_param();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
SyncedComponentConfig::_internal_mutable_custom_param() {
  return custom_param_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
SyncedComponentConfig::mutable_custom_param() {
  // @@protoc_insertion_point(field_mutable_map:senseAD.rscl.idl.SyncedComponentConfig.custom_param)
  return _internal_mutable_custom_param();
}

// repeated .senseAD.rscl.idl.ReaderOption readers = 3;
inline int SyncedComponentConfig::_internal_readers_size() const {
  return readers_.size();
}
inline int SyncedComponentConfig::readers_size() const {
  return _internal_readers_size();
}
inline void SyncedComponentConfig::clear_readers() {
  readers_.Clear();
}
inline ::senseAD::rscl::idl::ReaderOption* SyncedComponentConfig::mutable_readers(int index) {
  // @@protoc_insertion_point(field_mutable:senseAD.rscl.idl.SyncedComponentConfig.readers)
  return readers_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::senseAD::rscl::idl::ReaderOption >*
SyncedComponentConfig::mutable_readers() {
  // @@protoc_insertion_point(field_mutable_list:senseAD.rscl.idl.SyncedComponentConfig.readers)
  return &readers_;
}
inline const ::senseAD::rscl::idl::ReaderOption& SyncedComponentConfig::_internal_readers(int index) const {
  return readers_.Get(index);
}
inline const ::senseAD::rscl::idl::ReaderOption& SyncedComponentConfig::readers(int index) const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.SyncedComponentConfig.readers)
  return _internal_readers(index);
}
inline ::senseAD::rscl::idl::ReaderOption* SyncedComponentConfig::_internal_add_readers() {
  return readers_.Add();
}
inline ::senseAD::rscl::idl::ReaderOption* SyncedComponentConfig::add_readers() {
  // @@protoc_insertion_point(field_add:senseAD.rscl.idl.SyncedComponentConfig.readers)
  return _internal_add_readers();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::senseAD::rscl::idl::ReaderOption >&
SyncedComponentConfig::readers() const {
  // @@protoc_insertion_point(field_list:senseAD.rscl.idl.SyncedComponentConfig.readers)
  return readers_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// TimerComponentConfig

// optional string name = 1;
inline bool TimerComponentConfig::_internal_has_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool TimerComponentConfig::has_name() const {
  return _internal_has_name();
}
inline void TimerComponentConfig::clear_name() {
  name_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& TimerComponentConfig::name() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.TimerComponentConfig.name)
  return _internal_name();
}
inline void TimerComponentConfig::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:senseAD.rscl.idl.TimerComponentConfig.name)
}
inline std::string* TimerComponentConfig::mutable_name() {
  // @@protoc_insertion_point(field_mutable:senseAD.rscl.idl.TimerComponentConfig.name)
  return _internal_mutable_name();
}
inline const std::string& TimerComponentConfig::_internal_name() const {
  return name_.Get();
}
inline void TimerComponentConfig::_internal_set_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void TimerComponentConfig::set_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:senseAD.rscl.idl.TimerComponentConfig.name)
}
inline void TimerComponentConfig::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:senseAD.rscl.idl.TimerComponentConfig.name)
}
inline void TimerComponentConfig::set_name(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:senseAD.rscl.idl.TimerComponentConfig.name)
}
inline std::string* TimerComponentConfig::_internal_mutable_name() {
  _has_bits_[0] |= 0x00000001u;
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* TimerComponentConfig::release_name() {
  // @@protoc_insertion_point(field_release:senseAD.rscl.idl.TimerComponentConfig.name)
  if (!_internal_has_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return name_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TimerComponentConfig::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:senseAD.rscl.idl.TimerComponentConfig.name)
}

// map<string, string> custom_param = 2;
inline int TimerComponentConfig::_internal_custom_param_size() const {
  return custom_param_.size();
}
inline int TimerComponentConfig::custom_param_size() const {
  return _internal_custom_param_size();
}
inline void TimerComponentConfig::clear_custom_param() {
  custom_param_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
TimerComponentConfig::_internal_custom_param() const {
  return custom_param_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >&
TimerComponentConfig::custom_param() const {
  // @@protoc_insertion_point(field_map:senseAD.rscl.idl.TimerComponentConfig.custom_param)
  return _internal_custom_param();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
TimerComponentConfig::_internal_mutable_custom_param() {
  return custom_param_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >*
TimerComponentConfig::mutable_custom_param() {
  // @@protoc_insertion_point(field_mutable_map:senseAD.rscl.idl.TimerComponentConfig.custom_param)
  return _internal_mutable_custom_param();
}

// optional uint32 interval_ms = 3;
inline bool TimerComponentConfig::_internal_has_interval_ms() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool TimerComponentConfig::has_interval_ms() const {
  return _internal_has_interval_ms();
}
inline void TimerComponentConfig::clear_interval_ms() {
  interval_ms_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TimerComponentConfig::_internal_interval_ms() const {
  return interval_ms_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TimerComponentConfig::interval_ms() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.TimerComponentConfig.interval_ms)
  return _internal_interval_ms();
}
inline void TimerComponentConfig::_internal_set_interval_ms(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  interval_ms_ = value;
}
inline void TimerComponentConfig::set_interval_ms(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_interval_ms(value);
  // @@protoc_insertion_point(field_set:senseAD.rscl.idl.TimerComponentConfig.interval_ms)
}

// optional bool sim_time_interval = 4 [default = true];
inline bool TimerComponentConfig::_internal_has_sim_time_interval() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool TimerComponentConfig::has_sim_time_interval() const {
  return _internal_has_sim_time_interval();
}
inline void TimerComponentConfig::clear_sim_time_interval() {
  sim_time_interval_ = true;
  _has_bits_[0] &= ~0x00000004u;
}
inline bool TimerComponentConfig::_internal_sim_time_interval() const {
  return sim_time_interval_;
}
inline bool TimerComponentConfig::sim_time_interval() const {
  // @@protoc_insertion_point(field_get:senseAD.rscl.idl.TimerComponentConfig.sim_time_interval)
  return _internal_sim_time_interval();
}
inline void TimerComponentConfig::_internal_set_sim_time_interval(bool value) {
  _has_bits_[0] |= 0x00000004u;
  sim_time_interval_ = value;
}
inline void TimerComponentConfig::set_sim_time_interval(bool value) {
  _internal_set_sim_time_interval(value);
  // @@protoc_insertion_point(field_set:senseAD.rscl.idl.TimerComponentConfig.sim_time_interval)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace idl
}  // namespace rscl
}  // namespace senseAD

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ad_5frscl_2fidl_2fcomponent_5fconf_2eproto
