// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: hetero_channel_control.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 10002
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(d577b65c0f7dc8b3);
CAPNP_DECLARE_SCHEMA(df23c92fc9fff8cc);
enum class ControlType_df23c92fc9fff8cc: uint16_t {
  ENABLE_HETERO_CHANNEL,
  DISABLE_HETERO_CHANNEL,
};
CAPNP_DECLARE_ENUM(ControlType, df23c92fc9fff8cc);

}  // namespace schemas
}  // namespace capnp

namespace senseAD {
namespace rscl {
namespace idl {

struct ControlMessage {
  ControlMessage() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  typedef ::capnp::schemas::ControlType_df23c92fc9fff8cc ControlType;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(d577b65c0f7dc8b3, 1, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class ControlMessage::Reader {
public:
  typedef ControlMessage Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline  ::senseAD::rscl::idl::ControlMessage::ControlType getControlType() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class ControlMessage::Builder {
public:
  typedef ControlMessage Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline  ::senseAD::rscl::idl::ControlMessage::ControlType getControlType();
  inline void setControlType( ::senseAD::rscl::idl::ControlMessage::ControlType value);

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class ControlMessage::Pipeline {
public:
  typedef ControlMessage Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::senseAD::rscl::idl::ControlMessage::ControlType ControlMessage::Reader::getControlType() const {
  return _reader.getDataField< ::senseAD::rscl::idl::ControlMessage::ControlType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::senseAD::rscl::idl::ControlMessage::ControlType ControlMessage::Builder::getControlType() {
  return _builder.getDataField< ::senseAD::rscl::idl::ControlMessage::ControlType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void ControlMessage::Builder::setControlType( ::senseAD::rscl::idl::ControlMessage::ControlType value) {
  _builder.setDataField< ::senseAD::rscl::idl::ControlMessage::ControlType>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

}  // namespace
}  // namespace
}  // namespace

CAPNP_END_HEADER

